# Generated by Django 3.2.3 on 2021-05-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.nutrition'),
        ),
    ]
